header:
  version: 11

distro: poky

defaults:
  repos:
    refspec: master

repos:
  meta-arm:
    layers:
      meta-arm:
      meta-arm-bsp:
      meta-arm-toolchain:

  poky:
    url: https://git.yoctoproject.org/git/poky
    layers:
      meta:
      meta-poky:

env:
  BB_LOGCONFIG: ""
  TOOLCHAIN_DIR: ""

local_conf_header:
  base: |
    BB_SERVER_TIMEOUT = "60"
    CONF_VERSION = "2"
    PACKAGE_CLASSES = "package_ipk"
    LICENSE_FLAGS_WHITELIST += "armcompiler Arm-FVP-EULA"
    PACKAGECONFIG:remove:pn-qemu-system-native = "gtk+ sdl"
    EXTRA_IMAGE_FEATURES:append = " debug-tweaks"
    BB_NUMBER_THREADS = "16"
    PARALLEL_MAKE = "-j16"
    INHERIT += "rm_work"
    PACKAGECONFIG:append:pn-perf = " coresight"
  noptest: |
    DISTRO_FEATURES:remove = "ptest"
  kvm: |
    QEMU_USE_KVM = ""
  perf: |
    CORE_IMAGE_EXTRA_INSTALL += "perf"
machine: unset

target:
  - core-image-base
